//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCExpert.Core.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCExpert.Core.Domain.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components cannot be composed without cyclicly plugging some components to each other.
        /// </summary>
        public static string ConfigCyclicPluggingMsg {
            get {
                return ResourceManager.GetString("ConfigCyclicPluggingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration should contain {0}, but it is not added.
        /// </summary>
        public static string ConfigHasRequiredButNotAddedTypeMsg {
            get {
                return ResourceManager.GetString("ConfigHasRequiredButNotAddedTypeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration doesn&apos;t contain following required components: {0}.
        /// </summary>
        public static string ConfigHasRequiredButNotAddedTypesMsg {
            get {
                return ResourceManager.GetString("ConfigHasRequiredButNotAddedTypesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration name must be specified.
        /// </summary>
        public static string ConfigNameCannotBeEmptyMsg {
            get {
                return ResourceManager.GetString("ConfigNameCannotBeEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified name is already used.
        /// </summary>
        public static string ConfigNameNotUniqueMsg {
            get {
                return ResourceManager.GetString("ConfigNameNotUniqueMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration name should not be greater than 250 symbols.
        /// </summary>
        public static string ConfigNameTooLongMsg {
            get {
                return ResourceManager.GetString("ConfigNameTooLongMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration has more than one {0}.
        /// </summary>
        public static string ConfigTypesViolatedUniqueConstraintMsg {
            get {
                return ResourceManager.GetString("ConfigTypesViolatedUniqueConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name length should not be greater than 250 symbols.
        /// </summary>
        public static string NameTooLongMsg {
            get {
                return ResourceManager.GetString("NameTooLongMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name length should be at least 10.
        /// </summary>
        public static string NameTooShortMsg {
            get {
                return ResourceManager.GetString("NameTooShortMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price of the component cannot be negative.
        /// </summary>
        public static string NegativePriceMsg {
            get {
                return ResourceManager.GetString("NegativePriceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price of the component cannot be greater than 1000000$.
        /// </summary>
        public static string PriceTooGreateMsg {
            get {
                return ResourceManager.GetString("PriceTooGreateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save characteristic value that is not attached to component.
        /// </summary>
        public static string ValueShouldBeAttachedMsg {
            get {
                return ResourceManager.GetString("ValueShouldBeAttachedMsg", resourceCulture);
            }
        }
    }
}
